name: 'Build Flutter'
description: 'build flutter'
inputs:
  build_script:
    description: 'build script'
    required: true
    default: 'build_arm.sh'
  artifact_name:
    description: 'artifact name'
    required: true
    default: 'ARM'
runs:
  using: 'composite'
  steps:
    - uses: ./.github/actions/free_disk_space

    - name: Prepare Environment
      shell: bash
      run: |
        chmod +x ./scripts/*.sh
        ./scripts/prepare_environment.sh

    - name: Set Environment Variables
      shell: bash
      run: |
        source ./scripts/set_env.sh

    - name: Cache Flutter
      uses: actions/cache@v3
      with:
        path: |
          ./flutter
        key: flutter-${{ env.VERSION }}

    - name: Prepare Source
      shell: bash
      run: ./scripts/prepare_source.sh

    - name: Build
      shell: bash
      run: ./scripts/${{ inputs.build_script }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.artifact_name }}
        path: ./flutter/engine/src/lib
