name: Build Flutter Engine
on: push
jobs:
  build_arm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Environment
        run: ./scripts/prepare_environment.sh
      - name: Prepare Source
        run: ./scripts/prepare_source.sh
      - name: Build ARM
        run: ./scripts/build_arm.sh
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ARM
          path: flutter/engine/src/lib

  collect_and_release:
    runs-on: ubuntu-latest
    needs: [build_arm]
    steps:
      - uses: actions/checkout@v3
      - name: Collect ARM Artifacts
        uses: actions/download-artifact@v3
        with:
          name: ARM
      - name: Compress Artifacts
        run: ./scripts/compress_artifacts.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.head_commit.message }}
          files: |
            flutter/engine/src/lib.zip
          draft: false
          prerelease: false
