name: Build
on:
  workflow_call:
    inputs:
      build_script:
        description: 'build script'
        required: true
        type: string
        default: 'build_arm.sh'
      artifact_name:
        description: 'artifact name'
        required: true
        type: string
        default: 'ARM'
jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/free_disk_space

      - name: Prepare Environment
        run: |
          chmod +x ./scripts/*.sh
          ./scripts/prepare_environment.sh

      - name: Set Environment Variables
        run: |
          source ./scripts/set_env.sh

      - name: Cache Flutter
        uses: actions/cache@v3
        with:
          path: |
              ./flutter
          key: flutter-${{ env.VERSION }}

      - name: Prepare Source
        run: ./scripts/prepare_source.sh

      - name: Build
        run: ./scripts/${{ inputs.build_script }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact_name }}
          path: ./flutter/engine/src/libraries/flutter/lib/src/
