name: Build Flutter Engine
on: push
jobs:
  build_arm:
    runs-on: ubuntu-22.04
    env:
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build_flutter
        with:
          build_script: build_arm.sh
          artifact_name: ARM

  collect_and_release:
    runs-on: ubuntu-22.04
    needs: [build_arm]
    # needs: [build_arm, build_arm64, build_x64]
    steps:
      - uses: actions/checkout@v3

      - name: Collect ARM Artifacts
        uses: actions/download-artifact@v3
        with:
          name: ARM
        continue-on-error: true

      - name: Collect ARM64 Artifacts
        uses: actions/download-artifact@v3
        with:
          name: ARM64
        continue-on-error: true

      - name: Collect X64 Artifacts
        uses: actions/download-artifact@v3
        with:
          name: X64
        continue-on-error: true

      - name: Collect Artifacts
        run:  |
          chmod +x ./scripts/*.sh
          ./scripts/collect_artifacts.sh
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.head_commit.message }}
          files: |
            flutter/engine/src/lib.zip
          draft: false
          prerelease: false
