name: Build Flutter Engine
on: push
jobs:
  build_arm:
    uses: ./.github/workflows/build.yml
    with:
      build_script: build_arm.sh
      artifact_name: ARM

  build_arm64:
    uses: ./.github/workflows/build.yml
    with:
      build_script: build_arm64.sh
      artifact_name: ARM64

  build_x64:
    uses: ./.github/workflows/build.yml
    with:
      build_script: build_x64.sh
      artifact_name: X64

  collect_and_release:
    runs-on: ubuntu-22.04
    # needs: [build_arm]
    needs: [build_arm, build_arm64, build_x64]
    steps:
      - uses: actions/checkout@v3

      - name: Collect ARM Artifacts
        continue-on-error: true
        uses: actions/download-artifact@v3
        with:
          name: ARM
          path: ./flutter/engine/src/lib

      - name: Collect ARM64 Artifacts
        continue-on-error: true
        uses: actions/download-artifact@v3
        with:
          name: ARM64
          path: ./flutter/engine/src/lib

      - name: Collect X64 Artifacts
        continue-on-error: true
        uses: actions/download-artifact@v3
        with:
          name: X64
          path: ./flutter/engine/src/lib

      - name: Collect Artifacts
        run: |
          chmod +x ./scripts/*.sh
          ./scripts/collect_artifacts.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        # Settings -> Actions -> General -> Workflow permissions -> Read and write permissions
        with:
          tag_name: ${{ env.VERSION }}
          name: ${{ env.VERSION }}
          body: |
            ${{ github.event.head_commit.message }}
          files: |
            flutter/engine/src/lib.tar.gz
          draft: false
          prerelease: false
